include:
  - project: "mdz/devops/ci"
    file: "gitlab-ci-base.yml"

image: "$BUILD_IMAGE_ANSIBLE_MAVEN_JDK17"

variables:
  MAVEN_CLI_OPTS: "-Dmaven.repo.local=.m2/repository --batch-mode -Pcustom-nexus"
  PLAYBOOK: "cms/cudami.yml"

###################
### Stage build ###
###################

compile:
  variables:
    BUILD_PROFILE: production

